#! /usr/bin/tclsh
set message1 {
Make a file called sum1000.txt in the Lagoon that contains the sum of all the
numbers from one to one thousand.
}
set message2 {
Greetings. I hope you are enjoying Hunt Three. There two ways to figure out this
sum. One is to derive a formula, which is how a mathematician would do it.
Another is to write a program that adds all the numbers and gives you the sum,
which is how a computer programmer would do it.
}
puts $message1
puts -nonewline "The Hunt Manager would like to make a speech."
for {set i 0} {$i < 20} {incr i} {
	after 100
	puts -nonewline "."
	flush stdout
}
puts ""
set lines [split $message2 \n]
foreach line $lines {
	puts $line
	after 1000
}
puts "Thank you for your attention, carry on."